# Site Settings
title: Elections Site
email: apalacioscarrillo@gmail.com
description: >
  A guide to getting started with Jekyll.
baseurl: ''
url: 'http://localhost:4000'
twitter_username: apalaciosc
github_username: apalaciosc
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM